### ISSUE TITLE
Trying to get google access Token in android. Getting NullPointerException

### ISSUE THREAD

**Issue by khanfuad17** [googleapis/google-oauth-java-client#346] opened 2019-08-19 07:16 UTC
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
        at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127)
        at com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest.setCode(AuthorizationCodeTokenRequest.java:153)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.setCode(GoogleAuthorizationCodeTokenRequest.java:147)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.setCode(GoogleAuthorizationCodeTokenRequest.java:79)
        at com.google.api.client.auth.oauth2.AuthorizationCodeTokenRequest.<init>(AuthorizationCodeTokenRequest.java:103)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.<init>(GoogleAuthorizationCodeTokenRequest.java:111)

**Comment by chingor13** [comment] 2019-08-19 18:06
This NPE is thrown early because you are calling `AuthorizationCodeTokenRequest#setCode(String)` with a `null` value. If you trace through the call stack, you are trying to initialize a `GoogleAuthorizationCodeTokenRequest` with null for the `code` parameter.

**Comment by chingor13** [comment] 2019-09-10 04:53
Closing this as no additional information has been provided. Feel free to reopen if you can provide more information and the issue is still happening.

**Closed by chingor13** 2019-09-10 04:53 UTC
Labels: needs more info, type: question
